SELECT * FROM TAIKHOAN

--Tìm top 5 doanh thu phim 
WITH DOANHTHUPHIM AS
(
	SELECT 
	vxp.MAPHIM,
	SUM(SOVE * GIAVE) AS DOANHTHU
	FROM VEXEMPHIM vxp
	JOIN CTHD_VXP cthd_vxp ON cthd_vxp.MAVE = vxp.MAVE
	JOIN HOADON hd ON hd.SOHD = cthd_vxp.SOHD
	WHERE NGAYHD >= '2024-12-24' AND NGAYHD <= '2024-12-31'
	GROUP BY vxp.MAPHIM
)

SELECT TOP 5
	PHIM.TENPHIM,
	DOANHTHUPHIM.DOANHTHU AS TIEN
FROM DOANHTHUPHIM
RIGHT JOIN PHIM ON PHIM.MAPHIM = DOANHTHUPHIM.MAPHIM
ORDER BY DOANHTHUPHIM.DOANHTHU DESC;

--Tìm doanh thu theo ngày của cả rạp 
WITH TIMDOANHTHUPHIM AS
(
	SELECT 
		vxp.MAPHIM,
		SUM(SOVE * GIAVE) AS DOANHTHUp
	FROM VEXEMPHIM vxp
	JOIN CTHD_VXP cthd_vxp ON cthd_vxp.MAVE = vxp.MAVE
	JOIN HOADON hd ON hd.SOHD = cthd_vxp.MAVE
	WHERE NGAYHD = '2024-12-26'
	GROUP BY vxp.MAPHIM
),

TIMDOANHTHUSANPHAM AS
(
	SELECT 
		sp.MASP,
		SUM(SOSP * GIA) AS DOANHTHUsp
	FROM SANPHAM sp
	JOIN CTHD_SP cthd_sp ON cthd_sp.MASP = sp.MASP
	JOIN HOADON hd ON hd.SOHD = cthd_sp.SOHD
	WHERE NGAYHD =  '2024-12-26'
	GROUP BY sp.MASP
)

SELECT 
	COALESCE(SUM(DOANHTHUp), 0) + COALESCE(SUM(DOANHTHUsp), 0) AS TONGDOANHTHU
FROM 
	(SELECT SUM(DOANHTHUp) AS DOANHTHUp FROM TIMDOANHTHUPHIM) AS DOANHTHU_PHIM,
	(SELECT SUM(DOANHTHUsp) AS DOANHTHUsp FROM TIMDOANHTHUSANPHAM) AS DOANHTHU_SANPHAM;

--Tìm số vé phim bán được trong ngày 
SELECT 
	SUM(SOVE) AS SOVE
FROM CTHD_VXP cthd_vxp
JOIN HOADON hd ON hd.SOHD = cthd_vxp.SOHD
WHERE NGAYHD = '2024-12-26'

--Tìm hiệu suất của rạp 
WITH TIMTONGSOGHE AS
(
	SELECT 
		SUM(SOCHO) AS TONGSOGHE
	FROM RAPCHIEUPHIM
),

TIMTONGSOGHEDANGDUOCDUNG AS
(
	SELECT 
		COUNT(DISTINCT SOGHE) AS TONGSOGHEDANGDUOCDUNG
	FROM VEXEMPHIM vxp
	JOIN CTHD_VXP cthd ON vxp.MAVE = cthd.MAVE
	JOIN HOADON hd ON hd.SOHD = cthd.SOHD
	WHERE NGAYHD = '2024-12-28'
)

SELECT CAST (TONGSOGHEDANGDUOCDUNG AS FLOAT) / CAST (TONGSOGHE AS FLOAT) * 100 AS HIEUSUAT
FROM TIMTONGSOGHE, TIMTONGSOGHEDANGDUOCDUNG;

--Tìm số phim đang được chiếu
SELECT 
	COUNT(MAPHIM) AS SOPHIMDANGCHIEU
FROM PHIM
WHERE TINHTRANG = N'Đang chiếu';

SELECT * FROM PHIM;

--Tìm thông tin cá nhân của nhân viên
SELECT 
	tk.MANV,
	HOTEN,
	NGAYVL,
	SDT,
	GIOITINH,
	CHUCVU
FROM TAIKHOAN tk
JOIN NHANVIEN nv ON tk.MANV = nv.MANV
WHERE TENTK = 'admin1'

SELECT * FROM TAIKHOAN;
SELECT * FROM NHANVIEN;
UPDATE NHANVIEN
                               SET
                                    HOTEN = 'Kaguya Shinomiya',
                                    GIOITINH = N'Nữ',
                                    SDT = '12345678'
                               WHERE NHANVIEN.MANV = (SELECT nv.MANV
                                             FROM NHANVIEN nv JOIN TAIKHOAN tk ON tk.MANV = nv.MANV
                                             WHERE TENTK = 'kaguya')
SELECT * FROM PHIM;

DELETE FROM CTHD_VXP WHERE MAVE IN (SELECT MAVE FROM VEXEMPHIM WHERE MAPHIM = @MAPHIM)
DELETE FROM SUATCHIEU WHERE MAPHIM = @MAPHIM
DELETE FROM VEXEMPHIM WHERE MAPHIM = @MAPHIM
DELETE FROM PHIM WHERE MAPHIM = 'PH003'

SELECT * FROM VEXEMPHIM;
SELECT * FROM SUATCHIEU;

UPDATE PHIM
SET TENPHIM = @TENPHIM,
	THOILUONG = @THOILUONG,
	THELOAI = @THELOAI,
	DAODIEN = @DAODIEN,
	QUOCGIA = @QUOCGIA,
	NAMPH = @NAMPH,
	MOTA = @MOTA,
	TINHTRANG = @TINHTRANG,
	GIANHAP = @GIANHAP
WHERE MAPHIM = @MAPHIM;
	

DELETE FROM NHAPSP WHERE MANV = @MANV
DELETE FROM TAIKHOAN WHERE MANV = @MANV
DELETE FROM NHANVIEN WHERE MANV = @MANV
SELECT MATKHAU FROM TAIKHOAN WHERE TENTK = 'admin1'

ALTER TABLE PHIM
ADD ANHMINHOA NVARCHAR(255) NULL;

SELECT * FROM PHIM;

-- Tìm doanh thu kèm theo ngày
WITH TIMDOANHTHUPHIM AS
(
    SELECT 
        vxp.MAPHIM,
        hd.NGAYHD,
        SUM(SOVE * GIAVE) AS DOANHTHUp
    FROM VEXEMPHIM vxp
    JOIN CTHD_VXP cthd_vxp ON cthd_vxp.MAVE = vxp.MAVE
    JOIN HOADON hd ON hd.SOHD = cthd_vxp.MAVE
    WHERE NGAYHD = '2024-12-26'
    GROUP BY vxp.MAPHIM, hd.NGAYHD
),

TIMDOANHTHUSANPHAM AS
(
    SELECT 
        sp.MASP,
        hd.NGAYHD,
        SUM(SOSP * GIA) AS DOANHTHUsp
    FROM SANPHAM sp
    JOIN CTHD_SP cthd_sp ON cthd_sp.MASP = sp.MASP
    JOIN HOADON hd ON hd.SOHD = cthd_sp.SOHD
    WHERE NGAYHD = '2024-12-26'
    GROUP BY sp.MASP, hd.NGAYHD
)

SELECT 
    COALESCE(PHIM.NGAYHD, SP.NGAYHD) AS NGAYHD,
    COALESCE(SUM(PHIM.DOANHTHUp), 0) + COALESCE(SUM(SP.DOANHTHUsp), 0) AS TONGDOANHTHU
FROM 
    (SELECT NGAYHD, SUM(DOANHTHUp) AS DOANHTHUp FROM TIMDOANHTHUPHIM GROUP BY NGAYHD) AS PHIM
FULL JOIN 
    (SELECT NGAYHD, SUM(DOANHTHUsp) AS DOANHTHUsp FROM TIMDOANHTHUSANPHAM GROUP BY NGAYHD) AS SP
ON PHIM.NGAYHD = SP.NGAYHD
GROUP BY COALESCE(PHIM.NGAYHD, SP.NGAYHD);


-- Thêm cột SOLUONG vào bảng SANPHAM và tạo trigger tự động giảm số lượng sản phẩm khi có hóa đơn sản phẩm

ALTER TABLE SANPHAM
ADD SOLUONG int DEFAULT 0
UPDATE SANPHAM
SET SOLUONG = 0
WHERE SOLUONG IS NULL;

CREATE TRIGGER trg_UpdateSanPhamStock ON CTHD_SP
AFTER INSERT 
AS
BEGIN
    UPDATE SANPHAM
    SET SOLUONG = SOLUONG - INSERTED.SOSP
    FROM SANPHAM
    INNER JOIN INSERTED
    ON SANPHAM.MASP = INSERTED.MASP

    IF EXISTS (
        SELECT 1
        FROM SANPHAM
        WHERE SOLUONG < 0
    )
    BEGIN
        RAISERROR ('So luong san pham khong the am!', 16, 1)
        ROLLBACK TRANSACTION
    END
END;